=== Meg93/TraveSite15/XMLandXSD/travelSight.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="travelSightbase">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="about">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="title"/>
                            <xs:element name="author"/>
                            <xs:element ref="description"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="sourceDefs">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="sourceDef">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element ref="title"/>
                                        <xs:element ref="description"/>
                                        <xs:element name="url"/>
                                    </xs:sequence>
                                    <xs:attribute ref="id" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="travelSights">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="travelSight" maxOccurs="unbounded">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element ref="title"/>
                                        <xs:element ref="description"/>
                                        <xs:element name="sources">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element maxOccurs="unbounded"
                                                  name="sourceRefId" type="xs:IDREF"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="location"/>
                                        <xs:element name="pictures">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element maxOccurs="unbounded" name="picture">
                                                  <xs:complexType>
                                                  <xs:attribute name="path" use="required"/>
                                                  </xs:complexType>
                                                  </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="review" maxOccurs="unbounded">
                                            <xs:complexType mixed="true">
                                                <xs:sequence>
                                                  <xs:element name="p" maxOccurs="unbounded"
                                                  minOccurs="0"/>
                                                </xs:sequence>
                                                <xs:attribute ref="id" use="required"/>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="highLight" maxOccurs="unbounded"> </xs:element>
                                        <xs:element name="thingsToDo">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element maxOccurs="unbounded" name="thingToDo">
                                                  <xs:complexType>
                                                  <xs:sequence>
                                                  <xs:element ref="title"/>
                                                  <xs:element minOccurs="0" name="telephone"/>
                                                  <xs:element minOccurs="0" name="address"/>
                                                  <xs:element minOccurs="0" name="gettingThere"/>
                                                  <xs:element minOccurs="0" name="moreInfo"/>
                                                  <xs:element minOccurs="0" name="openHours"/>
                                                  </xs:sequence>
                                                  </xs:complexType>
                                                  </xs:element>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                        <xs:element name="associations">
                                            <xs:complexType>
                                                <xs:sequence>
                                                  <xs:element maxOccurs="unbounded" name="siteRefId"
                                                  type="xs:IDREF"/>
                                                </xs:sequence>
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                    <xs:attribute ref="id" use="required"/>
                                    <xs:attribute name="rank" use="required">
                                        <xs:simpleType>
                                            <xs:restriction base="xs:integer">
                                                <xs:enumeration value="1"/>
                                                <xs:enumeration value="2"/>
                                                <xs:enumeration value="3"/>
                                                <xs:enumeration value="4"/>
                                                <xs:enumeration value="5"/>
                                                <xs:enumeration value="6"/>
                                                <xs:enumeration value="7"/>
                                                <xs:enumeration value="8"/>
                                                <xs:enumeration value="9"/>
                                                <xs:enumeration value="10"/>
                                                <xs:enumeration value="11"/>
                                                <xs:enumeration value="12"/>
                                                <xs:enumeration value="13"/>
                                                <xs:enumeration value="14"/>
                                                <xs:enumeration value="15"/>
                                            </xs:restriction>
                                        </xs:simpleType>
                                    </xs:attribute>
                                    <xs:attribute name="tag" use="required"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="locations">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element ref="location"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
                <xs:element name="sequence">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="siteRefId" type="xs:IDREF"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="title"/>
    <xs:element name="description">
        <xs:complexType>
            <xs:group maxOccurs="unbounded" ref="block"/>
        </xs:complexType>
    </xs:element>
    <xs:attribute name="id" type="xs:ID"/>
    <xs:element name="a"/>
    <xs:element name="b"/>
    <xs:element name="i"/>
    <xs:element name="location">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="title"/>
                <xs:element maxOccurs="unbounded" minOccurs="0" name="siteRefId" type="xs:IDREF"/>
                <xs:element maxOccurs="unbounded" minOccurs="0" ref="location"/>
            </xs:sequence>
            <xs:attribute ref="id" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="xref">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="xrefText">
                    <xs:complexType mixed="true">
                        <xs:sequence>
                            <xs:element name="hotText"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute ref="id" use="required"/>
            <xs:attribute name="type" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:NMTOKEN">
                        <xs:enumeration value="off"/>
                        <xs:enumeration value="web"/>
                        <xs:enumeration value="local"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
            <xs:attribute name="dest" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="p">
        <xs:complexType mixed="true">
            <xs:group maxOccurs="unbounded" minOccurs="0" ref="inline"/>
        </xs:complexType>
    </xs:element>
    <xs:group name="block">
        <xs:choice>
            <xs:element ref="p"/>
            <xs:element ref="ul"/>
            <xs:element ref="ol"/>
            <xs:element ref="br"/>
            <xs:element ref="table"/>
            <xs:element name="media">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element ref="title"/>
                        <xs:element minOccurs="0" name="caption">
                            <xs:complexType mixed="true">
                                <xs:group ref="inline"/>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute ref="id" use="required"/>
                    <xs:attribute name="url" type="xs:string" use="required"/>
                    <xs:attribute name="type" use="required">
                        <xs:simpleType>
                            <xs:restriction base="xs:NMTOKEN">
                                <xs:enumeration value="imageWeb"/>
                                <xs:enumeration value="imageLocal"/>
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                    <xs:attribute name="style" type="xs:string"/>
                </xs:complexType>
            </xs:element>
            <xs:element ref="editor"/>
        </xs:choice>
    </xs:group>
    <xs:element name="ul">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                <xs:element ref="li"/>
                <xs:element minOccurs="0" ref="ul"/>
            </xs:choice>
        </xs:complexType>
    </xs:element>
    <xs:element name="ol">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded">
                <xs:element maxOccurs="unbounded" ref="li"/>
                <xs:element minOccurs="0" ref="ol"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element fixed="" name="br" nillable="true"/>
    <xs:element name="table">
        <xs:complexType>
            <xs:sequence maxOccurs="unbounded" minOccurs="0">
                <xs:element maxOccurs="unbounded" name="tr">
                    <xs:complexType mixed="false">
                        <xs:sequence>
                            <xs:element maxOccurs="unbounded" name="td">
                                <xs:complexType mixed="true">
                                    <xs:choice maxOccurs="unbounded">
                                        <xs:group ref="block"/>
                                    </xs:choice>
                                    <xs:attribute name="style" type="xs:string" use="optional"/>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="style" type="xs:string" use="optional"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
            <xs:attribute name="border" type="xs:string" use="optional"/>
            <xs:attribute name="cellSpacing" type="xs:string" use="optional"/>
            <xs:attribute name="cellPadding" type="xs:string" use="optional"/>
            <xs:attribute name="style" type="xs:string" use="optional"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="editor">
        <xs:complexType mixed="true">
            <xs:attribute name="showEdits" type="xs:boolean"/>
        </xs:complexType>
    </xs:element>
    <xs:group name="inline">
        <xs:choice>
            <xs:element minOccurs="0" ref="b"/>
            <xs:element minOccurs="0" ref="i"/>
            <xs:element minOccurs="0" ref="u"/>
            <xs:element minOccurs="0" ref="xref"/>
            <xs:element minOccurs="0" name="pubMentioned"/>
        </xs:choice>
    </xs:group>
    <xs:element name="u"/>
    <xs:element name="li">
        <xs:complexType mixed="true">
            <xs:group maxOccurs="unbounded" minOccurs="0" ref="inline"/>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== Meg93/TraveSite15/XMLandXSD/travelSight.xml
<?xml version="1.0" encoding="UTF-8"?>
<travelSightbase xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="travelSight.xsd">
    <about>
        <title>M &amp; T Travel Factory</title>
        <author>Meg Wang</author>
        <description>
            <p>Why we travel</p>
                <p>For us, travelling is one of our favorite hobbies. It is a time to relax and enjoy our stay in a environment different to what we have back at home. Travelling allows us to meet new people, new adventures, new food and new experiences. We travel to see what the world is like beyond our living room, classrooms and reading rooms.</p>                
                <p>We travel so we can lose ourselves in a world that we are trying to understand and find ourselves at the same time. Through travelling, we learn to open our eyes and immerse ourselves in a world that we have only seen through pictures and movies. We spend our money travelling but get richer in the process.</p>
            <p>By T</p>
            <ul>
                <li>NO.1 Maldives</li>
                <li>NO.2 Paris</li>
                <li>NO.3 Venice</li>
                <li>NO.4 Helsinki</li>
                <li>NO.5 Taiwan</li>
                <li>NO.6 Greece</li>
                <li>NO.7 Sydney</li>
                <li>NO.8 Cuba</li>
                <li>NO.9 Barcelona</li>
                <li>NO.10 London</li>
                <li>NO.11 Maui</li>
                <li>NO.12 Prague</li>
                <li>NO.13 Vancouver</li>
                <li>NO.14 Budapest</li>
                <li>NO.15 Hong Kong</li>
            </ul>
        </description>
    </about>

    <sourceDefs>
        <sourceDef id="s01">
            <title>visitMaldives</title>
            <description>
                <p>official website</p>
            </description>
            <url>http://www.visitmaldives.com/en</url>
        </sourceDef>
        <sourceDef id="s02">
            <title>gogobot</title>
            <description>
                <p>official website</p>
            </description>
            <url>www.gogobot.com</url>
        </sourceDef>
        <sourceDef id="s03">
            <title>Lonely Planet</title>
            <description>
                <p>official website</p>
            </description>
            <url>www.lonelyplanet.com/france</url>
        </sourceDef>
        <sourceDef id="s04">
            <title>Lonely Planet</title>
            <description>
                <p>official website</p>
            </description>
            <url>www.lonelyplanet.com/helsinki</url>
        </sourceDef>
        <sourceDef id="s05">
            <title>Lonely Planet</title>
            <description>
                <p>official website</p>
            </description>
            <url>www.lonelyplanet.com/</url>
        </sourceDef>
        <sourceDef id="s06">
            <title>Lonely Planet</title>
            <description>
                <p>official website</p>
            </description>
            <url>www.lonelyplanet.com/greece</url>
        </sourceDef>
        <sourceDef id="s07">
            <title>Lonely Planet</title>
            <description>
                <p>official website</p>
            </description>
            <url>www.lonelyplanet.com/australia</url>
        </sourceDef>
        <sourceDef id="s08">
            <title>Lonely Planet</title>
            <description>
                <p>official website</p>
            </description>
            <url>www.lonelyplanet.com/cuba</url>
        </sourceDef>
        <sourceDef id="s09">
            <title>Lonely Planet</title>
            <description>
                <p>official website</p>
            </description>
            <url>www.lonelyplanet.com/barcelona</url>
        </sourceDef>
        <sourceDef id="s10">
            <title>Lonely Planet</title>
            <description>
                <p>official website</p>
            </description>
            <url>www.lonelyplanet.com/london</url>
        </sourceDef>
        <sourceDef id="s11">
            <title>Lonely Planet</title>
            <description>
                <p>official website</p>
            </description>
            <url>www.lonelyplanet.com/</url>
        </sourceDef>
        <sourceDef id="s12">
            <title>Lonely Planet</title>
            <description>
                <p>official website</p>
            </description>
            <url>www.lonelyplanet.com/prague</url>
        </sourceDef>
        <sourceDef id="s13">
            <title>Lonely Planet</title>
            <description>
                <p>official website</p>
            </description>
            <url>www.lonelyplanet.com/vancouver</url>
        </sourceDef>
        <sourceDef id="s14">
            <title>Lonely Planet</title>
            <description>
                <p>official website</p>
            </description>
            <url>www.lonelyplanet.com/budapest</url>
        </sourceDef>
        <sourceDef id="s15">
            <title>Lonely Planet</title>
            <description>
                <p>official website</p>
            </description>
            <url>www.lonelyplanet.com/hongkong</url>
        </sourceDef>
    </sourceDefs>

    <travelSights>
        <travelSight id="site1" rank="1" tag="natural sight, diving, fishing, beach">
            <title>Maldives</title>
            <description>                
                <p><b>Welcome to the <u>Maldives!</u></b></p>
                <ul>
                    <li>Where <i>sands</i> are white as the smiles of the locals</li>
                    <li>Where <i>fish</i> swim happily in the warm waters of the Indian Ocean</li>
                    <li>Where the <i>weather</i> is a dream, and the deep rays of the sun waits to engulf
                        you in their arms</li>
                </ul>
                <p>For more information, please look into <pubMentioned>"Lonely Planet"</pubMentioned> 
                    <xref id="x01" type="web" dest="http://www.lonelyplanet.com/search?q=maldives">
                    <xrefText> (<hotText>http://www.lonelyplanet.com/search?q=maldives</hotText>) </xrefText>
                </xref>
                </p>
            </description>
            <sources>
                <sourceRefId>s01</sourceRefId>
                <sourceRefId>s02</sourceRefId>
            </sources>
            <location country="Republic of Maldives"/>
            <pictures>
                <picture path="maldives1.jpg"/>
            </pictures>
            <review id="r1">
                <p><b>Jelly</b>: What an amazing place. Be sure to be at the summit before the
                    sunrise. It's like seeing a sci-fi movie come to life. Recommended for: Outdoor
                    Enthusiasts</p>
            </review>
            <review id="r16">
                <p><b>Young</b>: Must see sunrise place. Worth the time to go there, be ready for
                    the cold though. Pack up some warm clothes. Recommended for: Backpackers History
                    Buffs Adventure Travelers</p>
            </review>
            <highLight>
                <p>The Maldives is the perfect destination for the most ardent of divers or for the
                    first time snorkeller with a huge range of marine biodiversity and exceptional
                    visibility </p>
             </highLight>
            <highLight>
                <p>You won't find a single echoey corridor anywhere in the Maldives</p>
            </highLight>


            <thingsToDo>
                <thingToDo>
                    <title>Outdoor Sports</title>
                    <telephone>206-777-7777</telephone>
                </thingToDo>
                <thingToDo>
                    <title>Fish Market</title>
                    <address>Boduthankurufaanu Magu, Malé, Maldives </address>
                </thingToDo>
                <thingToDo>
                    <title>National Museum</title>
                    <address>Chandhanee Magu, Malé, Maldives</address>
                    <openHours>10am-5pm Sun-Thu</openHours>
                </thingToDo>
            </thingsToDo>
            <associations>
                <siteRefId>site5</siteRefId>
                <siteRefId>site8</siteRefId>
                <siteRefId>site11</siteRefId>
            </associations>
        </travelSight>

        <travelSight id="site2" rank="2" tag="Romantic, Historical, Literatural">
            <title>Paris</title>
            <description>
                <p> France seduces travellers with its unfalteringly familiar culture, woven around
                    cafe terraces, village-square markets and lace-curtained bistros with their plat
                    du jour chalked on the board. </p>
            </description>
            <sources>
                <sourceRefId>s03</sourceRefId>
            </sources>
            <location country="France"/>
            <pictures>
                <picture path="paris1.jpg"/>
            </pictures>

            <review id="r2">
                <p> France has been home for two decades yet I can’t shake off that uncanny feeling
                    I’m on holiday – French art de vivre (art of living) is just too good and I’m
                    mad about it. From my Haute-Savoie house on Lake Geneva’s southern shore, the
                    dark green hills of the Jura and un café in the wisteria-draped village bar are
                    my wake-up call. Weekends of endless possibilities punctuate the gentle rhythm
                    of village life: ravishing art museums in Lyon and Paris, hiking and skiing in
                    the Alps, paddle boarding on the glittering lake, road trips to Beaujolais and
                    Burgundy and other regions so different they could be another country. France’s
                    sheer variety never ceases to amaze me. </p>
            </review>


            <highLight>
